name: Publish xmpp_dart to Pub.dev

on:
  push:
    branches:
      - "master"

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2 # required!
        
      - name: Test
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test --coverage --test-randomize-ordering-seed random
